language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#CI로 빌드 시, permission denied 떠서 여기서 권한주는 코드 추가.
before_install:
  - chmod +x gradlew

#Travis CI서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#밑의 deploy 명령어가 실행되기 전에 실행
before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 파일들 담을 디렉토리
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체압축
  - cd ../ && mkdir -p deploy # 상위디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springboot2-webservice.zip # deploy로 zip파일 이름 바꾼 후 이동

# AWS S3로 파일업로드 혹은 CodeDeploy로 배포등 외부 서비스와 연동될 행뒤들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값.(travis 홈피)
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값.(travis 홈피)
    bucket: springboot2-webservices-buildfiles # AWS S3 의 버킷명
    region: ap-northeast-2 # S3의 리전값. 아시아 태평양(서울)
    skip_cleanup: true
    acl: private # zip 파일접근을 private으로 설정
    local_dir: deploy # before_deploy에서 생성한 디렉토리. 해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot2-webservices-buildfiles
    key: springboot2-webservice.zip
    bundle_type: zip
    application: springboot2-webservice
    deployment_group: springboot2-webservice-buildgroup
    region: ap-northeast-2
    wait-untile-deployed: true


#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - rktldhkd@naver.com